import appSNC from '@mfelibs/universal-framework'
import '@mfelibs/universal-framework/src/libs/apis/hideLoading'
import '@mfelibs/universal-framework/src/libs/apis/fetch'
import '@mfelibs/universal-framework/src/libs/apis/openShare'
// import '@mfelibs/universal-framework/src/libs/apis/enablePullDownRefresh'
import '@mfelibs/universal-framework/src/libs/apis/stopPullDownRefresh'
import '@mfelibs/universal-framework/src/libs/apis/pageReload'
import '@mfelibs/universal-framework/src/libs/apis/pageError'
import '@mfelibs/universal-framework/src/libs/apis/login'
import '@mfelibs/universal-framework/src/libs/apis/shake'
import '@mfelibs/universal-framework/src/libs/apis/getUserInfo'
import '@mfelibs/universal-framework/src/libs/apis/showToast'
import '@mfelibs/universal-framework/src/libs/apis/getNetworkType'
import '@mfelibs/universal-framework/src/libs/apis/URLNavigateTo'
import '@mfelibs/universal-framework/src/libs/apis/setGlobalStorage'
export default appSNC
